### PR TITLE
Set svelte as a peerDependency, support, v3, v4 and v5-next

### LINKED ISSUE #230: Svelte 5 support
I understand Svelte 5 is still a preview release, but I'd love to be able to use this store with it. I believe since Svelte 5 is backwards compatible it should just work adding v5 to the `peerDependencies` chain.

Could throw together a PR if interested

### PR DESCRIPTION
**Pull request by danawoodman**
Fixes #230

### CODE REVIEW

**Comment by joshnuss** [comment]
Looks good!

One small thing: Can you add a commit message with a semantic commit messages `feat:`?
Without it, the package won't get pushed to the npm registry.

**Comment by danawoodman** [comment]
done!

**Comment by joshnuss** [comment]
Thanks @danawoodman!

**Comment by danawoodman** [comment]
Thank YOU @joshnuss !

**Pull request merged**
